// Code generated by antlr2participle. DO NOT EDIT.
package csv

import (
	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
)

var (
	Rules = lexer.Rules{
		"Root": {
			{"TEXT", `[^,\n\r"]+`, nil},
			{"STRING", `"(""|[^"])*"`, nil},
			{"XXX__LITERALS", `,|\n|\r`, nil},
		},
	}
	Lexer  = lexer.MustStateful(Rules, lexer.MatchLongest())
	Parser = participle.MustBuild(
		&CsvFile{},
		participle.Lexer(Lexer),
		participle.UseLookahead(2),
	)
)

type CsvFile struct {
	Hdr *Hdr   `@@`
	Row []*Row `@@+`
}
type Hdr struct {
	Row *Row `@@`
}
type Row struct {
	Field []*Field `@@? ( ',' @@? )* '\r'? '\n'?`
}
type Field struct {
	Text   *string `@TEXT`
	String *string `| @STRING`
}
