package antlr

var outputTemplate = `
// Code generated by antlr2participle. DO NOT EDIT.
package {{ .Grammar }}

import (
	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
)

var (
	Rules = lexer.Rules{
		"Root": {
			{{ .Rules }}
		},
	}
    Lexer = lexer.MustStateful(Rules, lexer.MatchLongest())
	Parser = participle.MustBuild(
		{{ .RootParseObj }}
		participle.Lexer(Lexer),
		participle.UseLookahead(2),
	)
)

{{ .ParseObjs }}
`
