#!/bin/bash
set -euo pipefail
GOBIN=$(go env GOBIN)
[[ -d "${GOBIN}" ]] || GOBIN=$(go env GOPATH)/bin
go install -C "$(dirname "$0")/../cmd/participle" 'github.com/alecthomas/participle/v2/cmd/participle'
exec "${GOBIN}/participle" "$@"
